### ISSUE TITLE
Player can buy Multiple Items ! [But script deducting only 1 Item's Price]

### ISSUE THREAD

**Issue by subhampro** [Flexiboi/flex-ownedshops#3]
If you purchase more then 1 item it will deduct only 1 Item's price [Another amount you will get at free of cost !!! ]

1 > Stock and / item Photo
![image](https://github.com/Flexiboi/flex-ownedshops/assets/33375250/e0d9bfdd-6d72-4a01-8233-d4a7adefa592)

2 > Inv Photo 
![image](https://github.com/Flexiboi/flex-ownedshops/assets/33375250/3b7d7f3b-6548-4744-a170-2261a917b0b3)

3 > Going to Buy !
![image](https://github.com/Flexiboi/flex-ownedshops/assets/33375250/a7d375ff-9bf1-4230-9b11-45b4b966c27f)

4 > At Notification Its Shows It Billed me 1 Lacks but deducted only 10,000 ! I get 9 Items Free of cost ! 
![image](https://github.com/Flexiboi/flex-ownedshops/assets/33375250/db455039-d159-4145-a72a-59955d03b697)

**Comment by Flexiboi** [comment]
Fixed and updated!
