### ISSUE TITLE
SCRIPT ERROR: @flex-ownedshops/server/main.lua:109: attempt to index a nil value (global 'item')

### ISSUE THREAD

**Issue by GyozaLion** [Flexiboi/flex-ownedshops#4]
![ss11](https://github.com/Flexiboi/flex-ownedshops/assets/115346313/17caf532-aa2c-46df-89f0-1a4a585565c3)

have some error after i change the test shop from job to gang, now it cant recieve any item

**Comment by Flexiboi** [comment]
Have you set the isjob > name to false?
Have you tried to rename the shop and added the sql?

**Comment by GyozaLion** [comment]
i did all the readme and change it based on the tutorial you give still the same error, so the error is like this
first i put an item to the shop it and it works after editing the price still works, but it's all get worse after someone buy the item from the shop, the the manage item list just empty, i try putting new item and the error got triggered

**Comment by Flexiboi** [comment]
I will try to have look asap

**Comment by Flexiboi** [comment]
For me when i edit it like this it works

<code>
[1] = {
        shopname = 'test', -- Name of shop
        shopprice = 1000, -- Price of this shop. When it is gang or job owned no need for price
        manageloc = vector4(-209.46, -633.75, 48.22, 180.2), -- Place where you manage the shop
        buyloc = vector4(-216.15, -632.02, 48.23, 262.22), -- Location to buy from shop
        target = true, -- If true it will spawn a vendingmachine at buyloc to target on
        isjob = {
            name = false, -- false to disable job
            everyone = true, -- true if all ranks can access
            dutyloc = vector4(-205.95, -627.39, 48.22, 248.61), -- nil to disable
        },
        isgang = {
            name = 'lostmc', -- false to disable gang
            everyone = true, -- true if all ranks can access
        },
        machine = {
            model = nil, -- Modelname or nil
            offset = { -- Ofset to the zone
                x = 0.0,
                y = 0.0,
                z = 0.0,
            }
        },
        ped = {
            model = 'a_f_m_ktown_02', -- Name of the ped or nil to disable
            scenario = 'WORLD_HUMAN_BINOCULARS', -- Scenario the ped will be dpoing
        },
        boxzone = {
            width = 2.0, -- Width of the target / box zone
            depth = 2.0, -- Depth of the target / box zone
            minZ = 2.0, -- Minz of the target zone (No need if not target)
            maxZ = 1.0, -- Maxz of the target zone (No need if not target)
        },
    },
<?code>

**Comment by Skutela32** [comment]
Did this get fixed? Im getting the same error.

**Comment by Skutela32** [comment]
So ive found the issue, when the DB table for stock becomes empty is when this error occurs. Only once it has been fully emptied

**Comment by Skutela32** [comment]
Issue can be resolved if you change db to [{}] manually although i cant figure out how to do it within the script so when its empty it sets itself to [{}] rather then []

**Comment by Flexiboi** [comment]
Just did a quick thing, not tested but i tried to check if it is empty. 
If it is empty i just added nothing to the db.
Try it and let me know

**Comment by Skutela32** [comment]
Nope same thing
![image](https://github.com/Flexiboi/flex-ownedshops/assets/96396382/fbbbf6f0-1e33-4861-8f56-36d31e0ef1be)
Just goes fully blank now

**Comment by Skutela32** [comment]
> Just did a quick thing, not tested but i tried to check if it is empty. If it is empty i just added nothing to the db. Try it and let me know

Check pull requests, now fixed
