### ISSUE TITLE
UI Reads Double The Actual Stock

### ISSUE THREAD

**Issue by Skutela32** [Flexiboi/flex-ownedshops#7]
![image](https://github.com/Flexiboi/flex-ownedshops/assets/96396382/93d577eb-2964-4179-886c-bf31da58276c)
![image](https://github.com/Flexiboi/flex-ownedshops/assets/96396382/a224d825-aaf3-4bf3-9d36-b7d7f947e85a)

It allows you to buy 2 of them aswell, if you purchase only 1 itll remove.
Im assuming its writing to the DB fine its just reading it double for some reason but im not sure where id find that.

**Comment by Skutela32** [comment]
Wait Fixed It!!! Itll Be In Pull Requests

**Comment by Flexiboi** [comment]
Legend good job thank!

**Comment by Skutela32** [comment]
No worries, any other bugs ill fix and follow it up with a push request later on. But at the moment no bugs so far.
